name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a command
        run: echo "Building mobile-app-react-native project"
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build